---
- name: "Change password on remote hosts"
  hosts: all:!localhost
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: "Get users list"
      ansible.builtin.command:
        cmd: "/usr/bin/cut -d: -f1 /etc/passwd"
      changed_when: false
      register: users_in_passwd

    - name: "End host if user does not exist in passwd"
      ansible.builtin.meta: end_host
      when:
        - username is not in users_in_passwd.stdout_lines
        - create_user == "no"

    - name: Hash the password
      ansible.builtin.set_fact:
        hashed_password: "{{ password | password_hash('sha512') }}"
      run_once: true
      no_log: true

    - name: "Reset local account password"
      ansible.builtin.user:
        name: "{{ username }}"
        update_password: always
        password: "{{ hashed_password }}"
        password_expire_max: "{{ 99999 if username == 'root' else 180 }}"
        local: true
      no_log: false

    - name: "Require to change password at next login"
      ansible.builtin.command: /usr/bin/chage -d 0 {{ username }}
      changed_when: false
      when:
        - require_to_change == "yes"
